In [1]:
import keras

Using TensorFlow backend.


In [2]:
from keras import metrics

In [3]:
# Check available tensorflow devices
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 7593794033368333819
]


In [54]:
# Set Theano config file to use device=gpu0 (previously it was set to device='cuda')
import os
os.environ['THEANO_FLAGS'] = "device='gpu0'"

In [55]:
import theano

In [56]:
# Can't change config.device value in code running in the same process.  Causes error:
# Exception: Can't change the value of this config parameter after initialization!
#
# import theano
# theano.config.device = 'gpu'
# theano.config.floatX = 'float32'

In [57]:
# Now let's check the device
# print(device_lib.list_local_devices())
print(theano.config.device)

cpu


In [58]:
# configure Thean to use GPU
theano.config.init_gpu_device

''

In [52]:
theano.config.force_device

False

In [53]:
theano.__version__

'1.0.1'

In [17]:
# import theano.sandbox.cuda
# theano.sandbox.cuda.use("gpu0")

# SkipTest: You are importing theano.sandbox.cuda. This is the old GPU back-end and is removed from Theano. Use Theano 0.9 to use it.
# Even better, transition to the new GPU back-end! See https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

In [18]:
# Check whether GPU is available with PyTorch (even though I'm using Keras/Theano in this project)
import torch
torch.cuda.is_available()

True

In [19]:
%pwd

'D:\\projects\\keras'

In [20]:
import numpy as np

In [21]:
import pandas as pd
import numpy as np

In [22]:
# df = pd.read_csv(‘Datasets/claims/insurance_claims.csv’)

In [23]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [59]:
# fix random seed for reproducibility
np.random.seed(7)

In [25]:
# load pima indians dataset
dataset = np.loadtxt("..\Jason_Brownlee\Datasets\pima-indians-diabetes.data.csv", delimiter=",")

In [26]:
dataset

array([[   6.   ,  148.   ,   72.   , ...,    0.627,   50.   ,    1.   ],
       [   1.   ,   85.   ,   66.   , ...,    0.351,   31.   ,    0.   ],
       [   8.   ,  183.   ,   64.   , ...,    0.672,   32.   ,    1.   ],
       ..., 
       [   5.   ,  121.   ,   72.   , ...,    0.245,   30.   ,    0.   ],
       [   1.   ,  126.   ,   60.   , ...,    0.349,   47.   ,    1.   ],
       [   1.   ,   93.   ,   70.   , ...,    0.315,   23.   ,    0.   ]])

In [27]:
type(dataset)

numpy.ndarray

In [28]:
# split into input (X) and output (Y) variables
X = dataset[:,0:8]
Y = dataset[:,8]

In [29]:
# Define Model
# create a sequential model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [30]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy', metrics.categorical_accuracy, 'mse', 'mae', 'mape', 'cosine'])
# There are several metrics out of the obx with Theano, so I'm just trying a few of them here.

In [31]:
# Fit the model
model.fit(X, Y, epochs=150, batch_size=10)

Epoch 1/150
768/768 [==============================] - 1s 660us/step - loss: 9.9578 - acc: 0.3438 - categorical_accuracy: 1.0000 - mean_squared_error: 0.6497 - mean_absolute_error: 0.6545 - mean_absolute_percentage_error: 625321043.6667 - cosine_proximity: -0.3377
Epoch 2/150
768/768 [==============================] - 0s 120us/step - loss: 5.4714 - acc: 0.4688 - categorical_accuracy: 1.0000 - mean_squared_error: 0.5051 - mean_absolute_error: 0.5365 - mean_absolute_percentage_error: 320941601.9947 - cosine_proximity: -0.2644
Epoch 3/150
768/768 [==============================] - 0s 160us/step - loss: 2.3252 - acc: 0.5234 - categorical_accuracy: 1.0000 - mean_squared_error: 0.3929 - mean_absolute_error: 0.4674 - mean_absolute_percentage_error: 227008663.5208 - cosine_proximity: -0.3051
Epoch 4/150
768/768 [==============================] - 0s 119us/step - loss: 1.8493 - acc: 0.5690 - categorical_accuracy: 1.0000 - mean_squared_error: 0.3385 - mean_absolute_error: 0.4258 - mean_absolute_p

In [32]:
# evaluate the model
scores = model.evaluate(X, Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

768/768 [==============================] - 0s 63us/step

acc: 78.65%


In [33]:
model.metrics_names

['loss',
 'acc',
 'categorical_accuracy',
 'mean_squared_error',
 'mean_absolute_error',
 'mean_absolute_percentage_error',
 'cosine_proximity']

## Make Predictions

In [34]:
# calculate predictions
predictions = model.predict(X)

In [35]:
predictions

array([[  8.06661248e-01],
       [  9.97103229e-02],
       [  8.63128722e-01],
       [  7.90348202e-02],
       [  6.25111997e-01],
       [  2.07243353e-01],
       [  1.33099392e-01],
       [  4.17390376e-01],
       [  9.66335058e-01],
       [  2.67306685e-01],
       [  2.11074665e-01],
       [  9.21547353e-01],
       [  3.96052837e-01],
       [  8.15170109e-01],
       [  6.89052045e-01],
       [  2.37959757e-01],
       [  5.06699562e-01],
       [  3.16575706e-01],
       [  2.95702547e-01],
       [  1.73313171e-01],
       [  4.65527296e-01],
       [  2.79957801e-01],
       [  9.05242026e-01],
       [  2.87488520e-01],
       [  6.34334683e-01],
       [  4.79524851e-01],
       [  8.34693730e-01],
       [  7.19764978e-02],
       [  6.27675712e-01],
       [  2.66518831e-01],
       [  5.25187790e-01],
       [  6.50171399e-01],
       [  4.49616425e-02],
       [  3.53078656e-02],
       [  5.36625624e-01],
       [  4.05336946e-01],
       [  7.42508292e-01],
 

In [36]:
import matplotlib.pyplot as plt
%matplotlib inline
%matplotlib notebook

In [37]:
import ipywidgets
ipywidgets.__version__

'7.0.0'

In [38]:
num_bins = 50
fig, ax = plt.subplots()

<IPython.core.display.Javascript object>

In [39]:
n, bins, patches = ax.hist(predictions, num_bins, density=1)

In [40]:
fig.tight_layout()
plt.show()
# Hmmm, unfortunately looks like Jupyter Lab hasn't enabled/allowed widgets to be displayed in Jupyter notebook, so I can't see the plot generated.
# "JavaScript output is disabled in JupyterLab"

In [41]:
bins

array([  2.62217072e-04,   1.97218077e-02,   3.91813982e-02,
         5.86409888e-02,   7.81005794e-02,   9.75601700e-02,
         1.17019761e-01,   1.36479351e-01,   1.55938942e-01,
         1.75398532e-01,   1.94858123e-01,   2.14317714e-01,
         2.33777304e-01,   2.53236895e-01,   2.72696485e-01,
         2.92156076e-01,   3.11615666e-01,   3.31075257e-01,
         3.50534848e-01,   3.69994438e-01,   3.89454029e-01,
         4.08913619e-01,   4.28373210e-01,   4.47832801e-01,
         4.67292391e-01,   4.86751982e-01,   5.06211572e-01,
         5.25671163e-01,   5.45130754e-01,   5.64590344e-01,
         5.84049935e-01,   6.03509525e-01,   6.22969116e-01,
         6.42428706e-01,   6.61888297e-01,   6.81347888e-01,
         7.00807478e-01,   7.20267069e-01,   7.39726659e-01,
         7.59186250e-01,   7.78645841e-01,   7.98105431e-01,
         8.17565022e-01,   8.37024612e-01,   8.56484203e-01,
         8.75943793e-01,   8.95403384e-01,   9.14862975e-01,
         9.34322565e-01,

In [42]:
# round predictions
rounded = [round(x[0]) for x in predictions]
print(rounded)

[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0,

In [43]:
# Count num of 1s
sum(x for x in rounded if x==1)

230.0

In [44]:
len(rounded)

768

In [45]:
# So 297 out of 768 predictions were True (i.e. ~39%)